/**
 * @file Automatically generated by barrelsby.
 */

export * from "./core/ModifiableToken";
export * from "./core/StringableEntity";
export * from "./core/Token";
export * from "./core/TokenizableStringableEntity";
export * from "./core/interfaces/IClassifier";
export * from "./core/interfaces/IClonable";
export * from "./core/interfaces/IQuote";
export * from "./core/interfaces/IRule";
export * from "./core/interfaces/IStringable";
export * from "./core/interfaces/ITypeMarked";
export * from "./lexicology/enums/LexicologyVerbalType";
export * from "./orthography/Char";
export * from "./orthography/Digraph";
export * from "./orthography/Letter";
export * from "./orthography/Meta";
export * from "./orthography/Phone";
export * from "./orthography/PhoneIpa";
export * from "./orthography/Sentence";
export * from "./orthography/Text";
export * from "./orthography/Voice";
export * from "./orthography/Word";
export * from "./orthography/WordStem";
export * from "./phonetics/Consonant";
export * from "./phonetics/Diphthong";
export * from "./phonetics/Syllable";
export * from "./phonetics/Vowel";
export * from "./semantics/EmailAddress";
export * from "./semantics/PhoneNumber";
export * from "./semantics/Url";
export * from "./sematics/enums/SentenceModality";
